{% set version = "0.0.1" %}

package:
  name: conda-whl-support
  version: {{ version }}

source:
  path: ..

build:
  script:
    - SETUPTOOLS_SCM_PRETEND_VERSION={{version}} python -m pip install . -vv
  noarch: python

requirements:
  host:
    - python >=3.9
    - pip
    - hatchling
    - hatch-vcs
  run:
    - python >=3.9
    - conda >=24
    - python-installer

test:
  imports:
    - conda_whl_support

about:
  summary: "Plugin to add support for installing whl files in conda"
